language: go
install: true
go:
  - 1.8.x
  - master
env:
  global:
    - GOARCH=amd64
script:
  - make coverage
services:
  - mongodb
notifications:
  email:
    on_success: change
    on_failure: always
